source 'https://rubygems.org'

gem 'execjs'
gem 'haml'
gem 'haml_coffee_assets'
gem 'uglifier'
gem 'sinatra'
gem 'sequel'
gem 'sprockets'
gem 'sprockets-helpers'
gem 'dependor-sinatra'
gem 'therubyracer'
gem 'wiringpi'
gem 'thin'
gem 'sqlite3'
gem 'sass'