source 'http://gems.github.com'
source 'https://rubygems.org'

gem 'execjs'
gem 'haml'
gem 'haml_coffee_assets'
gem 'uglifier'
gem 'sinatra'
gem 'sequel'
gem 'sprockets'
gem 'sprockets-helpers'
gem 'dependor-sinatra'
gem 'therubyracer'
gem 'wiringpi'
gem 'thin'
gem 'sqlite3'
gem 'sass'
gem 'binding_of_caller'
gem 'pry'
gem 'warden'
gem 'bcrypt-ruby'
gem 'memcache-client'
gem 'dalli'
gem 'nokogiri'
gem 'yui-compressor'
gem 'rake'
gem 'capistrano'
# gem 'capistrano-rvm'
gem 'rvm1-capistrano3', require: false