source 'https://rubygems.org'

gem 'execjs'
gem 'haml'
gem 'haml_coffee_assets'
gem 'uglifier'
gem 'sinatra'
gem 'sinatra-asset-pipeline'
gem 'sequel'
gem 'dependor'
gem 'therubyracer'
gem 'wiringpi'
gem 'thin'
gem 'sqlite3'