skirace:
  application:
    locale:
      default_locale: pl

    config:
      memcache_server: localhost:11211
      memcache_options:
        namespace: skirace
        compress: true
  raspberry_pi:
    config:
      gpio: